### ISSUE TITLE
Support single texture file export

### ISSUE THREAD

**Issue by erodozer** [pez2k/gt2tools#4]
I'm currently working on an application where I'd like to be able to render the exported GT2 car models in Godot engine.
My flow for making that work so far has been

- Use GT2ModelTool to export to OBJ
- Use GT2TextureEditor to dump bmp files
- use obj2gltf to make a gltf from the obj (Godot preserves the mesh groups this way so I can read the wheelpos and also disable the other LOD models)
- procedurally render a wheel mesh at each of the wheel pos vertices

https://user-images.githubusercontent.com/316728/231010124-30eaa847-b2cc-43b9-97ef-701176c80c22.mp4

This has worked mostly fine, but there are some differences between using the OBJs that these CLI tools produced and the ones created by GT2 Car Viewer v0.2.  The better scale factor and wheel pos values have been key in streamlining importing.

However, GT2 Car Viewer was able to export a baked texture to a single TGA with alpha for each car palette, which is a lot more portable and compatible.  The mesh is also simpler, by being just a single merged surface instead of having a surface for each polygon group, and only requires a singular texture bind.  

I'm looking for similar export functionality, so that the model may render more accurately and so that it's easier to swap materials/colors.

**Comment by erodozer** [comment]
Gonna leave this open since I think it's still useful for the sake of helping get these models rendered and portable in all kinds of engines.

However, for Godot I'm now investigating reimplementing the model parsing and texture parsing as an importer for the engine.  Thank you for the research and open sourcing of your work, it's helping me tremendously.

**Comment by pez2k** [comment]
Sorry, I completely missed that you'd posted this issue!

The GT2ModelTool and GT2TextureEditor code is focused mostly on editing models and textures, so having the separate materials is essential to be able to round-trip back into CDO, as the CDP textures consist of one bitmap image with 16 palettes. GT2TextureEditor alone can't produce a single 'flattened' texture as that needs knowledge of the model, and vice-versa with GT2ModelTool, as they're intentionally quite simple stand-alone tools to get file editing up and running quickly.

GT2CarViewer on the other hand is, as you suggest, more focused on portable, simpler model exports, with the caveat that they can't be re-imported. From the sound of it you will have seen in its code how it colours the texture based on the UV map for export. There's definitely a need for a successor to it with the newer research incorporated, but my focus is more on initial editing tools for a wide variety of the game's formats currently.

Implementing your own importer to fit your needs is definitely the way to go, and I'm glad this code has been useful to do so - I only got this far due to Leo and commongear open-sourcing their research and tools, so it's only right for me to pass that on.

**Comment by erodozer** [comment]
Sounds good!  I'll close this ticket then and continue work on my plugins, basing mostly off of this repo's research.  Hopefully it can help lead to a new generation of open source graphical tools for working with the files.
